### ISSUE TITLE
As a student using NodeBB, I want to be able to see the classes section on the home page so I an easily find my classes.

### ISSUE THREAD

**Issue by mingminggl** [CMU-313/fall23-nodebb-fam#12]
0. Most important out of all the issues, or else users will not be able to access it from the landing page

**Comment by adityaganesh0309** [comment]
Estimated Effort: 1 Day

Dependencies: None

Acceptance Criteria:
     - See a classes section on the home page

**Comment by mingminggl** [comment]
https://github.com/CMU-313/fall23-nodebb-fam/commit/f198ba8eff04381565ed01162b06c3c8a3ec4f35

**Comment by mingminggl** [comment]
https://github.com/CMU-313/fall23-nodebb-fam/commit/f198ba8eff04381565ed01162b06c3c8a3ec4f35

**Comment by Fakpabio** [comment]
View:

![Image](https://github.com/CMU-313/fall23-nodebb-fam/assets/107285974/20e9dc2c-d4fc-4ed4-bb59-05fa5c635069)
