### ISSUE TITLE
As an instructor using NodeBB, I want to be able make a class so that I can organize questions for my students.

### ISSUE THREAD

**Issue by Fakpabio** [CMU-313/fall23-nodebb-fam#2]
1. This user story serves as the foundation for the entire context of our project. Without implementing the ability to create a class, instructors and students have no way of using NodeBB as intended.

**Comment by adityaganesh0309** [comment]
Estimated Effort: 2 Day

Dependencies: None

Acceptance Criteria:
     - See a class section on the home page

**Comment by adityaganesh0309** [comment]
The create group feature was used for this. Ryan is currently working on changing any reference of group to say class.

![Image](https://github.com/CMU-313/fall23-nodebb-fam/assets/45804847/d5019921-ec10-470e-8473-a7f567b9b731)
