### ISSUE TITLE
As a student using NodeBB, I want to see a list of my classes so that I can go to a Q/A for any of them.

### ISSUE THREAD

**Issue by Fakpabio** [CMU-313/fall23-nodebb-fam#3]
2. In Canvas, students have the ability to view a list of all of their classes so that they can navigate to class-specific discussions. This is an essential part of the layout of a course-management system, so it should be highly. prioritized.

**Comment by adityaganesh0309** [comment]
Estimated Effort: 1 Day

Dependencies: Story #2 

Acceptance Criteria:
     - See a list of class in the classes section

**Comment by adityaganesh0309** [comment]
Edit: This user story was a duplicate of one we newly created after changing our development plans.

**Comment by mingminggl** [comment]
Students are now be able to see a list of their classes in the groups section
