### ISSUE TITLE
As a student using NodeBB, I want to be able to create a question within my class so that I can get an answer to my question.

### ISSUE THREAD

**Issue by Fakpabio** [CMU-313/fall23-nodebb-fam#4]
3. Without the ability to ask questions, this platform provides no use to students.

**Comment by mingminggl** [comment]
Estimated Effort: 2 Days

Dependencies: https://github.com/CMU-313/fall23-nodebb-fam/issues/3

Acceptance Criteria:
- Create a question in my class.

**Comment by adityaganesh0309** [comment]
Edit: This user story is no longer necessary as per our new plan for the platform. Questions will be posted using the existing feature through a category.

**Comment by mingminggl** [comment]
See above
