### ISSUE TITLE
As an instructor using NodeBB, I want to be able to reply to my students' questions so that they can learn better.

### ISSUE THREAD

**Issue by Fakpabio** [CMU-313/fall23-nodebb-fam#5]
4. This feature is also paramount to the functionality of this platform. If instructors can't reply to their students, then it serves no real purpose to the students asking questions.

**Comment by adityaganesh0309** [comment]
Estimated Effort: 1 Day

Dependencies: Story #4 

Acceptance Criteria:
- See a reply to an existing question
- See the option to reply to an existing question

**Comment by adityaganesh0309** [comment]
Edit: This feature no longer needs to be completed due to changes in our development plans. Using the existing category structure, instructors can already reply to any questions posted there.

**Comment by mingminggl** [comment]
This feature is already available as part of NodeBB's 'reply' function

**Comment by mingminggl** [comment]
We changed the name of the pages including one that is named 'Question & Answers'

**Comment by mingminggl** [comment]
> We changed the name of the pages including one that is named 'Question & Answers'
