### ISSUE TITLE
As an instructor using NodeBB, I want to see whether a question is solved or not so that I can identify which questions I need to answer.

### ISSUE THREAD

**Issue by Fakpabio** [CMU-313/fall23-nodebb-fam#7]
6. Another ease-of-use feature, which makes it easier for instructors to focus on questions that aren't answered. It isn't a higher priority since the core functions of the feature still work without it.

**Comment by adityaganesh0309** [comment]
Estimated Effort: 1 Day

Dependencies: Story #4 

Acceptance Criteria:
- See an option to mark a question as resolved
- See that question is marked as resolved/unresolved
