### ISSUE TITLE
As a student using NodeBB, I want to be able to insert an image in a post I create so that my professor can easily understand my question.

### ISSUE THREAD

**Issue by Fakpabio** [CMU-313/fall23-nodebb-fam#8]
7. This feature allows students to display to instructors the work they are doing since some questions require images. Not a higher ranking since core functionality is asking questions.

**Comment by adityaganesh0309** [comment]
Estimated Effort: 1 Day

Dependencies: Story #4 

Acceptance Criteria:
- See the option to add an image to a question
- See an image posted with a question

**Comment by adityaganesh0309** [comment]
Edit: this feature already works; closing it and adding a new one
